apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: a2a-digital-twin
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "__PRODUCTION_DOMAIN__"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: a2a-digital-twin
                port:
                  number: 80
