"""
integrations/office/graph_checkpoint.py

Microsoft Office checkpoints via Microsoft Graph API.
No desktop required — pure REST.

Creates checkpoints at each Workflow Stage completion:
  - Word doc   → agent handoff report (mirrors HANDOFF.md pattern from A2A_MCP)
  - Excel      → metrics dashboard (test pass rate, task completion, coverage)
  - Outlook    → sends handoff email to next agent/human in workflow

Authentication: Azure AD App Registration with Graph API permissions:
  - Files.ReadWrite (for Word/Excel via OneDrive)
  - Mail.Send (for Outlook)
  - Sites.ReadWrite.All (for SharePoint if used)

Setup: set env vars OFFICE_TENANT_ID, OFFICE_CLIENT_ID, OFFICE_CLIENT_SECRET
"""

from __future__ import annotations

import base64
import json
import os
from datetime import datetime
from typing import Any

import httpx

TENANT_ID = os.environ.get("OFFICE_TENANT_ID", "")
CLIENT_ID = os.environ.get("OFFICE_CLIENT_ID", "")
CLIENT_SECRET = os.environ.get("OFFICE_CLIENT_SECRET", "")
USER_EMAIL = os.environ.get("OFFICE_USER_EMAIL", "")      # who to file docs under
GRAPH_BASE = "https://graph.microsoft.com/v1.0"


# ── Auth ──────────────────────────────────────────────────────────────────────
async def get_access_token() -> str:
    """Get OAuth2 client credentials token for Microsoft Graph."""
    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/token",
            data={
                "grant_type": "client_credentials",
                "client_id": CLIENT_ID,
                "client_secret": CLIENT_SECRET,
                "scope": "https://graph.microsoft.com/.default",
            },
        )
        resp.raise_for_status()
        return resp.json()["access_token"]


def _auth_headers(token: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


# ── Word: Handoff Report ──────────────────────────────────────────────────────
async def create_word_handoff(
    task_name: str,
    agent_id: str,
    stage: str,
    summary: str,
    acceptance_criteria: list[str],
    fossil_hashes: list[str],
    next_agent: str = "",
) -> dict[str, str]:
    """
    Creates a Word document handoff report in OneDrive.
    Mirrors the HANDOFF.md pattern from A2A_MCP but as a proper .docx.

    Returns {"ok": True, "url": "<sharepoint_url>", "file_id": "..."}
    """
    token = await get_access_token()

    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"Handoff_{task_name.replace(' ', '_')}_{timestamp}.docx"

    # Build simple HTML content (Graph API converts to .docx)
    criteria_html = "".join(f"<li>{c}</li>" for c in acceptance_criteria)
    fossil_html = "".join(f"<li><code>{h}</code></li>" for h in fossil_hashes)
    next_html = f"<p><strong>Next Agent:</strong> {next_agent}</p>" if next_agent else ""

    html_content = f"""
    <html><body>
    <h1>Handoff Report: {task_name}</h1>
    <p><strong>Agent:</strong> {agent_id} | <strong>Stage:</strong> {stage}</p>
    <p><strong>Timestamp:</strong> {datetime.utcnow().isoformat()}Z</p>
    <h2>Summary</h2><p>{summary}</p>
    <h2>Acceptance Criteria</h2><ul>{criteria_html}</ul>
    <h2>Fossil Chain Hashes (Audit)</h2><ul>{fossil_html}</ul>
    {next_html}
    <hr/><p><em>Generated by A2A Digital Twin — adaptco-main/A2A_MCP</em></p>
    </body></html>
    """

    # Upload HTML to OneDrive (Graph converts to .docx on download)
    async with httpx.AsyncClient() as client:
        resp = await client.put(
            f"{GRAPH_BASE}/users/{USER_EMAIL}/drive/root:/A2A_Digital_Twin/{filename}:/content",
            headers={**_auth_headers(token), "Content-Type": "text/html"},
            content=html_content.encode(),
        )
        resp.raise_for_status()
        data = resp.json()

    return {
        "ok": True,
        "filename": filename,
        "file_id": data.get("id", ""),
        "url": data.get("webUrl", ""),
    }


# ── Excel: Metrics Dashboard ──────────────────────────────────────────────────
async def update_excel_metrics(
    metrics: dict[str, Any],
    workbook_name: str = "A2A_Digital_Twin_Metrics.xlsx",
) -> dict[str, str]:
    """
    Updates (or creates) an Excel workbook with current metrics.
    Writes to the 'Metrics' sheet with a timestamped row.

    metrics dict should include:
        task_name, agent_id, stage, passed_tests, failed_tests,
        coverage_pct, tasks_done, tasks_total, ci_status
    """
    token = await get_access_token()

    # Check if workbook exists
    async with httpx.AsyncClient() as client:
        check = await client.get(
            f"{GRAPH_BASE}/users/{USER_EMAIL}/drive/root:/A2A_Digital_Twin/{workbook_name}",
            headers=_auth_headers(token),
        )

        if check.status_code == 404:
            # Create new workbook (can't create .xlsx directly via Graph easily,
            # so we upload a minimal template)
            await _create_excel_template(token, workbook_name)

        # Get workbook item id
        item_resp = await client.get(
            f"{GRAPH_BASE}/users/{USER_EMAIL}/drive/root:/A2A_Digital_Twin/{workbook_name}",
            headers=_auth_headers(token),
        )
        item_resp.raise_for_status()
        item_id = item_resp.json()["id"]

        # Append row to Metrics worksheet
        row = [
            datetime.utcnow().isoformat(),
            metrics.get("task_name", ""),
            metrics.get("agent_id", ""),
            metrics.get("stage", ""),
            metrics.get("passed_tests", 0),
            metrics.get("failed_tests", 0),
            metrics.get("coverage_pct", 0.0),
            metrics.get("tasks_done", 0),
            metrics.get("tasks_total", 0),
            metrics.get("ci_status", ""),
        ]

        range_resp = await client.post(
            f"{GRAPH_BASE}/users/{USER_EMAIL}/drive/items/{item_id}/workbook/worksheets/Metrics/tables/MetricsTable/rows/add",
            headers=_auth_headers(token),
            json={"values": [row]},
        )
        range_resp.raise_for_status()

    return {"ok": True, "workbook": workbook_name}


async def _create_excel_template(token: str, name: str) -> None:
    """Upload a minimal Excel template to OneDrive."""
    # In production, upload a pre-built .xlsx template from disk
    # For now we note the file needs to be pre-created with a MetricsTable
    pass


# ── Outlook: Handoff Email ────────────────────────────────────────────────────
async def send_outlook_handoff(
    to_email: str,
    task_name: str,
    agent_id: str,
    stage: str,
    summary: str,
    word_doc_url: str = "",
    excel_url: str = "",
) -> dict[str, str]:
    """
    Sends a handoff email via Outlook/Exchange using Microsoft Graph.
    """
    token = await get_access_token()

    body = f"""
    <h2>🤖 A2A Digital Twin — Stage Complete: {stage}</h2>
    <p><strong>Task:</strong> {task_name}</p>
    <p><strong>Completed by:</strong> {agent_id}</p>
    <p><strong>Summary:</strong> {summary}</p>
    """
    if word_doc_url:
        body += f'<p>📄 <a href="{word_doc_url}">Handoff Document (Word)</a></p>'
    if excel_url:
        body += f'<p>📊 <a href="{excel_url}">Metrics Dashboard (Excel)</a></p>'
    body += "<hr/><p><em>Sent by A2A Digital Twin — adaptco-main/A2A_MCP</em></p>"

    email_payload = {
        "message": {
            "subject": f"[A2A Twin] Stage Complete: {stage} — {task_name}",
            "body": {"contentType": "HTML", "content": body},
            "toRecipients": [{"emailAddress": {"address": to_email}}],
        },
        "saveToSentItems": True,
    }

    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"{GRAPH_BASE}/users/{USER_EMAIL}/sendMail",
            headers=_auth_headers(token),
            json=email_payload,
        )
        resp.raise_for_status()

    return {"ok": True, "sent_to": to_email, "subject": email_payload["message"]["subject"]}


# ── Unified checkpoint writer ─────────────────────────────────────────────────
async def write_stage_checkpoint(
    task_name: str,
    agent_id: str,
    stage: str,
    summary: str,
    acceptance_criteria: list[str],
    fossil_hashes: list[str],
    metrics: dict[str, Any],
    checkpoint_type: str = "all",    # "word" | "excel" | "outlook" | "all"
    handoff_email: str = "",
    next_agent: str = "",
) -> dict[str, Any]:
    """
    Single call to write all Office checkpoints for a workflow stage completion.
    Called by IntentEngine after each stage finishes.
    """
    results: dict[str, Any] = {"stage": stage, "task": task_name}

    if checkpoint_type in ("word", "all"):
        results["word"] = await create_word_handoff(
            task_name, agent_id, stage, summary,
            acceptance_criteria, fossil_hashes, next_agent,
        )

    if checkpoint_type in ("excel", "all"):
        results["excel"] = await update_excel_metrics(metrics)

    if checkpoint_type in ("outlook", "all") and handoff_email:
        results["outlook"] = await send_outlook_handoff(
            to_email=handoff_email,
            task_name=task_name,
            agent_id=agent_id,
            stage=stage,
            summary=summary,
            word_doc_url=results.get("word", {}).get("url", ""),
            excel_url=results.get("excel", {}).get("workbook", ""),
        )

    return results
